apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  containers:
  - env:
    - name: INFLUXDB_HOST
      value: influxdb
    - name: PG_HOST
      value: postgres
    - name: PG_USERNAME
      value: postgres
    image: eu.gcr.io/sense-219918/sense_app:latest
    name: app
    ports:
    - containerPort: 4000
    resources: {}
    stdin: true
    tty: true
  restartPolicy: OnFailure
  volumes:
  - name: app-claim0
    persistentVolumeClaim:
      claimName: app-claim0
status: {}
