apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: mqtt
  name: mqtt
spec:
  ports:
  - name: "1883"
    port: 1883
    targetPort: 1883
  - name: "9883"
    port: 9883
    targetPort: 9883
  selector:
    io.kompose.service: mqtt
status:
  loadBalancer: {}
