apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: mqtt
  name: mqtt
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mqtt
    spec:
      containers:
      - env:
        - name: EMQX_WAIT_TIME
          value: '60'
        - name: EMQX_LOADED_PLUGINS
          value: 'emqx_recon,emqx_retainer,emqx_management,emqx_dashboard, emqx_auth_http'
        - name: EMQX_ADMIN_PASSWORD
          value: 'p455w0rd'
        - name: EMQX_AUTH__HTTP__AUTH_REQ
          value: 'http://app:4000/mqtt/user'
        - name: EMQX_AUTH__HTTP__AUTH_REQ__method
          value: 'post'
        - name: EMQX_AUTH__HTTP__AUTH_REQ__params
          value: 'clientid=%c,username=%u,password=%P'
        - name: EMQX_AUTH__HTTP__SUPER_REQ
          value: 'http://app:4000/mqtt/superuser'
        - name: EMQX_AUTH__HTTP__SUPER_REQ__method
          value: 'post'
        - name: EMQX_AUTH__HTTP__SUPER_REQ__params
          value: 'clientid=%c,username=%u'
        - name: EMQX_AUTH__HTTP__ACL_REQ
          value: 'http://app:4000/mqtt/acl'
        - name: EMQX_AUTH__HTTP__ACL_REQ__method
          value: 'post'
        - name: EMQX_AUTH__HTTP__ACL_REQ__params
          value: 'access=username=%u,topic=%t'
        - name: EMQX_LOG__CONSOLE
          value: 'console'
        - name: EMQX_LOG__CONSOLE__LEVEL
          value: 'debug'
        image: emqx/emqx:latest
        name: mqtt
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 8083
          name: ws
        resources:
          requests:
            cpu: "10m"
      restartPolicy: Always
status: {}
