apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: mqtt
  name: mqtt
spec:
  ports:
  - name: "mqtt"
    port: 1883
    targetPort: 1883
  - name: "ws"
    port: 8083
    targetPort: 8083
  selector:
    io.kompose.service: mqtt
status:
  loadBalancer: {}
