apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: sense_dev
        - name: POSTGRES_USER
          value: postgres
        image: postgres:9.6.3
        name: postgres
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: "250m"
      restartPolicy: Always
status: {}
