apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  containers:
  - env:
    - name: API_HOST
      value: app
    image: eu.gcr.io/sense-219918/sense_web:latest
    name: web
    ports:
    - containerPort: 4200
    resources: {}
    stdin: true
    tty: true
  restartPolicy: OnFailure
  volumes:
  - name: web-claim0
    persistentVolumeClaim:
      claimName: web-claim0
status: {}
