apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: webapp
  name: webapp
  namespace: senseapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: webapp
    spec:
      containers:
      - env:
        - name: INFLUXDB_HOST
          value: influxdb
        - name: PG_HOST
          value: postgres
        - name: PG_USERNAME
          value: postgres
        image: basestylo/sense_web:1570984827
        name: app
        ports:
          - containerPort: 4200
        resources:
          requests:
            cpu: "10m"
      restartPolicy: Always
