web:
  build: .
  user: $UID
  command: bash -c "mix deps.get && npm install && node node_modules/brunch/bin/brunch build && mix ecto.migrate && mix phoenix.server"
  environment:
    - INFLUXDB_HOST=influxdb
    - PG_HOST=postgres
    - PG_USERNAME=postgres
  volumes:
    - .:/app
  ports:
    - 4000:4000
  links:
    - postgres
    - influxdb
  stdin_open: true
  tty: true
  
postgres:
  image: postgres:9.6.3
  ports:
    - 5432
    
influxdb:
  image: influxdb:1.2.4
  ports:
    - 8086:8086
    - 8083:8083
