apiVersion: v1
kind: Pod
metadata:
  name: run-seeds-on-app
  namespace: senseapp
spec:
  containers:
  - name: db-migration
    image: basestylo/sense_app:latest
    resources:
      requests:
        cpu: "10m"
    command: ["mix"]
    args: ["do", "ecto.seeds"]
    env:
      - name: MIX_ENV
        value: prod
      - name: INFLUXDB_HOST
        value: influxdb
      - name: PG_HOST
        value: postgres
      - name: PG_USERNAME
        value: postgres
  restartPolicy: Never
